### ISSUE TITLE
Curl error while publishing into dataverse

### ISSUE THREAD

**Issue by wheintz** [eblondel/atom4R#1]
Hi Emmanuel,
I did some other test publishing into data.inrae.fr from the rstudio server Gedeop. I thought it came from my colleague's configuration but it's more about mine! Indeed, we did a test with another colleague's account and he got the same error : 
```
1  atom4R      TRUE     0.1
[atom4R][WARN] SwordDataverseClient - Token is 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
[atom4R][INFO] SwordDataverseClient - GET - Sword Dataverse service document at 'https://data.inrae.fr/dvn/api/data-deposit/v1.1/swordv2/service-document'
Error in curl::curl_fetch_memory(url, handle = handle) :
  error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
In addition: Warning messages:
1: In default_backend_auto() :
  Selecting ‘env’ backend. Secrets are stored in environment variables
2: In default_backend_auto() :
  Selecting ‘env’ backend. Secrets are stored in environment variables
3: In default_backend_auto() :
  Selecting ‘env’ backend. Secrets are stored in environment variables
[atom4R][ERROR] SwordDataverseClient - Error while retrieving SWORD service document
 
Error in super$initialize(url = sword_api_url, version = "2", token = token,  :
  Error while retrieving SWORD service document
```
On my rstudio session, I don't get this error, whatever the token used. So it seems that I'm the only one able to publish ...

Thanks for your help!

**Comment by eblondel** [comment]
I've tested it on my local Rstudio and on the D4Science e-infra Rstudio it works well. This issue let indicates an issue with the curl config on your Rstudio server:

```
error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
```
Looking at most of threads, it indicates the need to decrease SSL security level: See eg https://askubuntu.com/questions/1233186/ubuntu-20-04-how-to-set-lower-ssl-security-level

**Comment by wheintz** [comment]
Hello Emmanuel,

Many thanks, it works for me!

`sudo nano /etc/ssl/openssl.cnf`

Add this line at the top:
`
openssl_conf = openssl_init`

And add these lines at the end:

```
[openssl_init]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
CipherString = DEFAULT@SECLEVEL=1
```
Cheers,

 Wilfried
