### ISSUE TITLE
Support new setter methods for list of elements

### ISSUE THREAD

**Issue by mpadge** [eblondel/atom4R#14]
``` r
library(atom4R)
packageVersion ("atom4R")
#> [1] '0.2.9999'
d <- atom4R::DCEntry$new ()
d$addDCCreator (c ("a", "b"))
d$validate ()
#> Error in if (Encoding(out) != "UTF-8") out <- iconv(out, to = "UTF-8"): the condition has length > 1
```

<sup>Created on 2022-05-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Obviously it's been coded with the assumption that a Creator entry is a single string, but confirming that needs to be part of the validation step. (And actually the Creator term permits Creator as an Agent and by extension Agent Class, so multiple entries should be permitted.)

**Comment by eblondel** [comment]
addDCCreator, as any add* methods expect a single value, see examples at ?DCEntry . Controls will be added to prevent from adding vectors of length > 1.
If you want to specify a list of creators, either you call _addDCCreator_ as many times you need. (These functions check for an existing item first, and return FALSE, if not added);, or you can set directly the dc$creator field which is public.  I may add additional methods like `setDCCreators` as convenience if needed.

Multiple entries are already permitted then but will be set as sequence of the same xml field name in the XML.

See the example:

```R
 d <- atom4R::DCEntry$new()
d$addDCCreator("Bob Marley")
d$addDCCreator("Peter Tosh")
d$addDCCreator("Bunny Wailer")
xml = d$encode() #encode() will check for validity by default
```
