### ISSUE TITLE
bug in "updated" timestamp

### ISSUE THREAD

**Issue by mpadge** [eblondel/atom4R#17]
No matter what I do, all DCEntry objects always have the same time stamp. The first timestamp in this reprex is when I did the system install of the package, and the second produces the timestamp when `load_all()` is called. Even then, subsequent calls after the second of those repeat that same timestamp, and do not ever set it to the expected value of `Sys.time()`.

``` r
library (atom4R)
dcmi <- atom4R::DCEntry$new ()
dcmi$updated
#> [1] "2022-05-19 11:45:51 CEST"
Sys.time () - dcmi$updated
#> Time difference of 4.596361 hours

path <- "/<path>/<to>/<local>/atom4R"
devtools::load_all (path, export_all = FALSE)
#> ℹ Loading atom4R
dcmi <- atom4R::DCEntry$new ()
dcmi$updated
#> [1] "2022-05-19 16:21:39 CEST"
Sys.time () - dcmi$updated
#> Time difference of 1.471567 secs
```

<sup>Created on 2022-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by eblondel** [comment]
hum i see, i should set it when initializing object. Pushing a fix right now.

**Comment by mpadge** [comment]
Thanks, that's better
